apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: result-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: maletq/result:latest
        ports:
        - containerPort: 80
      volumes:
      - name: result-storage
        persistentVolumeClaim:
          claimName: result-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
