apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vote-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: maletq/vote:latest
        ports:
        - containerPort: 5000
      volumes:
      - name: vote-storage
        persistentVolumeClaim:
          claimName: vote-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
